<?php
add_action( 'wp_enqueue_scripts', 'enqueue_markers_scripts' );
function enqueue_markers_scripts() {
	if ( is_page_template( 'templates/vueTemplate.php' ) ) {
		// register the Vue build script.
		wp_register_script( // the app build script generated by Webpack.
			'vue_map_app',
			//get_stylesheet_directory_uri() . '/markers/dist/build.js',
			'http://localhost:8080/dist/build.js',
			array(),
			false,
			true
		);
    	// enqueue the Vue app script with localized data.
		wp_enqueue_script( 'vue_map_app' );
	}
}
